"""product images barcodes notifications and tournament engine

Revision ID: 23ca203f6f8f
Revises: 95164b3da6a0
Create Date: 2026-09-03 22:15:06.872506

"""
from alembic import context, op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23ca203f6f8f'
down_revision = '95164b3da6a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Las bases locales anteriores ya tenían algunas tablas creadas sin esta
    # revisión de Alembic. En una migración normal las inspeccionamos para no
    # recrearlas; en la generación SQL offline no hay conexión que inspeccionar
    # y se parte de una base nueva, por lo que deben emitirse todas las tablas.
    existing_tables = (
        set()
        if context.is_offline_mode()
        else set(sa.inspect(op.get_bind()).get_table_names())
    )
    if 'notifications' not in existing_tables:
        op.create_table('notifications',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('category', sa.String(length=30), nullable=False, server_default='INFO'),
        sa.Column('title', sa.String(length=160), nullable=False),
        sa.Column('message', sa.String(length=300), nullable=False),
        sa.Column('link', sa.String(length=255), nullable=True),
        sa.Column('is_read', sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('notifications', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
            batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    if 'tournament_groups' not in existing_tables:
        op.create_table('tournament_groups',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tournament_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=40), nullable=False),
        sa.Column('position', sa.Integer(), nullable=False, server_default='1'),
        sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tournament_id', 'name', name='uq_tournament_group_name')
        )
        with op.batch_alter_table('tournament_groups', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_tournament_groups_tournament_id'), ['tournament_id'], unique=False)

    if 'tournament_entries' not in existing_tables:
        op.create_table('tournament_entries',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tournament_id', sa.Integer(), nullable=False),
        sa.Column('team_id', sa.Integer(), nullable=False),
        sa.Column('group_id', sa.Integer(), nullable=True),
        sa.Column('fee_amount', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0'),
        sa.Column('paid_amount', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0'),
        sa.Column('payment_status', sa.String(length=20), nullable=False, server_default='PENDIENTE'),
        sa.Column('seed', sa.Integer(), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=False),
        sa.Column('registered_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['group_id'], ['tournament_groups.id'], ),
        sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
        sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tournament_id', 'team_id', name='uq_tournament_entry_team')
        )
        with op.batch_alter_table('tournament_entries', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_tournament_entries_team_id'), ['team_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_tournament_entries_tournament_id'), ['tournament_id'], unique=False)

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stage', sa.String(length=20), nullable=False, server_default='GROUP'))
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('round_number', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('round_name', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('matchday', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('bracket_position', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('next_match_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('next_slot', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('winner_team_id', sa.Integer(), nullable=True))
        batch_op.alter_column('home_team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('away_team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('start_time',
               existing_type=sa.TIME(),
               nullable=True)
        batch_op.create_foreign_key('fk_matches_next_match', 'matches', ['next_match_id'], ['id'])
        batch_op.create_foreign_key('fk_matches_group', 'tournament_groups', ['group_id'], ['id'])
        batch_op.create_foreign_key('fk_matches_winner', 'teams', ['winner_team_id'], ['id'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tournament_entry_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_payments_tournament_entry', 'tournament_entries', ['tournament_entry_id'], ['id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barcode', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_products_barcode'), ['barcode'], unique=True)

    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_fee', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('group_count', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('qualifiers_per_group', sa.Integer(), nullable=False, server_default='2'))
        batch_op.add_column(sa.Column('draw_completed', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('bracket_generated', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('champion_team_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_tournaments_champion', 'teams', ['champion_team_id'], ['id'])

    op.execute("UPDATE tournaments SET format = 'ROUND_ROBIN' WHERE format = 'Todos contra todos'")
    op.execute("UPDATE tournaments SET format = 'KNOCKOUT' WHERE format IN ('Eliminación directa', 'Eliminacion directa')")
    op.execute("UPDATE tournaments SET format = 'GROUPS_KNOCKOUT', group_count = CASE WHEN group_count < 2 THEN 2 ELSE group_count END WHERE format IN ('Grupos + Playoffs', 'Grupos + eliminación', 'Grupos + eliminacion')")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tournaments_champion', type_='foreignkey')
        batch_op.drop_column('champion_team_id')
        batch_op.drop_column('bracket_generated')
        batch_op.drop_column('draw_completed')
        batch_op.drop_column('qualifiers_per_group')
        batch_op.drop_column('group_count')
        batch_op.drop_column('registration_fee')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_barcode'))
        batch_op.drop_column('barcode')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payments_tournament_entry', type_='foreignkey')
        batch_op.drop_column('tournament_entry_id')

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_constraint('fk_matches_winner', type_='foreignkey')
        batch_op.drop_constraint('fk_matches_group', type_='foreignkey')
        batch_op.drop_constraint('fk_matches_next_match', type_='foreignkey')
        batch_op.alter_column('start_time',
               existing_type=sa.TIME(),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('away_team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('home_team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('winner_team_id')
        batch_op.drop_column('next_slot')
        batch_op.drop_column('next_match_id')
        batch_op.drop_column('bracket_position')
        batch_op.drop_column('matchday')
        batch_op.drop_column('round_name')
        batch_op.drop_column('round_number')
        batch_op.drop_column('group_id')
        batch_op.drop_column('stage')

    with op.batch_alter_table('tournament_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tournament_entries_tournament_id'))
        batch_op.drop_index(batch_op.f('ix_tournament_entries_team_id'))

    op.drop_table('tournament_entries')
    with op.batch_alter_table('tournament_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tournament_groups_tournament_id'))

    op.drop_table('tournament_groups')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    # ### end Alembic commands ###
